//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDigBioEntities : DbContext
    {
        public iDigBioEntities()
            : base("name=iDigBioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OCRCachedResult> OCRCachedResults { get; set; }
        public DbSet<ParsingResult> ParsingResults { get; set; }
        public DbSet<ProcessEngine> ProcessEngines { get; set; }
        public DbSet<SourceImage> SourceImages { get; set; }
        public DbSet<SourceImageProcessRequest> SourceImageProcessRequests { get; set; }
        public DbSet<SourceImageRepository> SourceImageRepositories { get; set; }
        public DbSet<SourceImageRepositoryProcessEngineConfig> SourceImageRepositoryProcessEngineConfigs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
