//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCRCachedResult
    {
        public int ocrCachedResultId { get; set; }
        public System.Guid sourceImageId { get; set; }
        public int processEngineId { get; set; }
        public string value { get; set; }
    
        public virtual ProcessEngine ProcessEngine { get; set; }
        public virtual SourceImage SourceImage { get; set; }
    }
}
