//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParsingResult
    {
        public int parsingResultId { get; set; }
        public string fileNameIdentifier { get; set; }
        public Nullable<System.Guid> sourceUUID { get; set; }
        public string dwcrecordedBy { get; set; }
        public string dwcrecordNumber { get; set; }
        public string dwcverbatimCoordinates { get; set; }
        public string dwcverbatimEventDate { get; set; }
        public string dwceventDate { get; set; }
        public string dwcmunicipality { get; set; }
        public string dwccounty { get; set; }
        public string dwcstateProvince { get; set; }
        public string dwccountry { get; set; }
        public string aocrverbatimScientificName { get; set; }
        public string dwcverbatimLocality { get; set; }
        public string dwchabitat { get; set; }
        public string dwcsubstrate { get; set; }
        public string dwcverbatimElevation { get; set; }
        public string dwcidentifiedBy { get; set; }
        public string dwcdateIdentified { get; set; }
        public string dwcverbatimLatitude { get; set; }
        public string dwcverbatimLongitude { get; set; }
        public string dwccatalogNumber { get; set; }
        public string aocrverbatimInstitution { get; set; }
        public string dwcdatasetName { get; set; }
        public string dwcscientificName { get; set; }
        public string dwcdecimalLatitude { get; set; }
        public string dwcdecimalLongitude { get; set; }
        public string dwcfieldNotes { get; set; }
        public string dwcsex { get; set; }
        public string createdByUserName { get; set; }
        public System.DateTime createdUTCDateTime { get; set; }
        public string ipAddress { get; set; }
    }
}
