//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessEngine
    {
        public ProcessEngine()
        {
            this.OCRCachedResults = new HashSet<OCRCachedResult>();
            this.SourceImageProcessRequests = new HashSet<SourceImageProcessRequest>();
            this.SourceImageRepositoryProcessEngineConfigs = new HashSet<SourceImageRepositoryProcessEngineConfig>();
        }
    
        public int processEngineId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<OCRCachedResult> OCRCachedResults { get; set; }
        public virtual ICollection<SourceImageProcessRequest> SourceImageProcessRequests { get; set; }
        public virtual ICollection<SourceImageRepositoryProcessEngineConfig> SourceImageRepositoryProcessEngineConfigs { get; set; }
    }
}
