//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceImageRepository
    {
        public SourceImageRepository()
        {
            this.SourceImages = new HashSet<SourceImage>();
            this.SourceImageRepositoryProcessEngineConfigs = new HashSet<SourceImageRepositoryProcessEngineConfig>();
        }
    
        public System.Guid sourceImageRepositoryId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<SourceImage> SourceImages { get; set; }
        public virtual ICollection<SourceImageRepositoryProcessEngineConfig> SourceImageRepositoryProcessEngineConfigs { get; set; }
    }
}
