//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDigBio.RESTService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceImageRepositoryProcessEngineConfig
    {
        public System.Guid sourceImageRepositoryId { get; set; }
        public int processEngineId { get; set; }
        public string environment { get; set; }
        public string outputDirectoryPath { get; set; }
        public bool useOCRSimulatedResult { get; set; }
    
        public virtual ProcessEngine ProcessEngine { get; set; }
        public virtual SourceImageRepository SourceImageRepository { get; set; }
    }
}
