CREATE TABLE [dbo].[ParsingResults] (
    [parsingResultId]            INT              IDENTITY (1, 1) NOT NULL,
    [fileNameIdentifier]         NVARCHAR (100)   NULL,
    [sourceUUID]                 UNIQUEIDENTIFIER NULL,
    [dwcrecordedBy]              NVARCHAR (500)   NULL,
    [dwcrecordNumber]            NVARCHAR (500)   NULL,
    [dwcverbatimCoordinates]     NVARCHAR (500)   NULL,
    [dwcverbatimEventDate]       NVARCHAR (500)   NULL,
    [dwceventDate]               NVARCHAR (500)   NULL,
    [dwcmunicipality]            NVARCHAR (500)   NULL,
    [dwccounty]                  NVARCHAR (500)   NULL,
    [dwcstateProvince]           NVARCHAR (500)   NULL,
    [dwccountry]                 NVARCHAR (500)   NULL,
    [aocrverbatimScientificName] NVARCHAR (500)   NULL,
    [dwcverbatimLocality]        NVARCHAR (500)   NULL,
    [dwchabitat]                 NVARCHAR (500)   NULL,
    [dwcsubstrate]               NVARCHAR (500)   NULL,
    [dwcverbatimElevation]       NVARCHAR (500)   NULL,
    [dwcidentifiedBy]            NVARCHAR (500)   NULL,
    [dwcdateIdentified]          NVARCHAR (500)   NULL,
    [dwcverbatimLatitude]        NVARCHAR (500)   NULL,
    [dwcverbatimLongitude]       NVARCHAR (500)   NULL,
    [dwccatalogNumber]           NVARCHAR (500)   NULL,
    [aocrverbatimInstitution]    NVARCHAR (500)   NULL,
    [dwcdatasetName]             NVARCHAR (500)   NULL,
    [dwcscientificName]          NVARCHAR (500)   NULL,
    [dwcdecimalLatitude]         NVARCHAR (500)   NULL,
    [dwcdecimalLongitude]        NVARCHAR (500)   NULL,
    [dwcfieldNotes]              NVARCHAR (500)   NULL,
    [dwcsex]                     NVARCHAR (500)   NULL,
    [createdByUserName]          NVARCHAR (50)    NULL,
    [createdUTCDateTime]         DATETIME         CONSTRAINT [DF_ParsingResults_createdUTCDatetime] DEFAULT (getutcdate()) NOT NULL,
    [ipAddress]                  NVARCHAR (50)    NULL,
    CONSTRAINT [PK_ParsingResults] PRIMARY KEY CLUSTERED ([parsingResultId] ASC)
);

